
export const GET_CATS_REQUEST = "GET_CATS_REQUEST";
export const GET_CATS_SUCCESS = "GET_CATS_SUCCESS";
export const GET_CATS_ERROR = "GET_CATS_ERROR";

export const UPLOAD_CAT_REQUEST = "UPLOAD_CAT_REQUEST";
export const UPLOAD_CAT_SUCCESS = "UPLOAD_CAT_SUCCESS";
export const UPLOAD_CAT_ERROR = "UPLOAD_CAT_ERROR";

export const FAV_CAT_REQUEST = "FAV_CAT_REQUEST";
export const FAV_CAT_SUCCESS = "FAV_CAT_SUCCESS";
export const FAV_CAT_ERROR = "FAV_CAT_ERROR";

export const DELETE_FAV_CAT_REQUEST = "DELETE_FAV_CAT_REQUEST";
export const DELETE_FAV_CAT_SUCCESS = "DELETE_FAV_CAT_SUCCESS";
export const DELETE_FAV_CAT_ERROR = "DELETE_FAV_CAT_ERROR";

export const VOTE_CAT_REQUEST = "VOTE_CAT_REQUEST";
export const VOTE_CAT_SUCCESS = "VOTE_CAT_SUCCESS";
export const VOTE_CAT_ERROR = "VOTE_CAT_ERROR";

export const GET_VOTES_SUCCESS ="GET_VOTES_SUCCESS";
export const GET_FAVOURITES_SUCCESS = "GET_FAVOURITES_SUCCESS";